sudo: required
dist: trusty

language: haskell 

services:
  - docker

before_install:
- docker pull fpco/stack-build:lts-5.12
- cd web && docker build --tag cirrusbuild .
- docker run cirrusbuild /bin/sh -c'cd /build && stack install' 