* Cirrus - An AdWords Data Platform
This repository contains a selection of tools for downloading AdWords
data and inserting it into an SQL database.

It is very much work in progress. You should email me at 
richard.fergie@gmail.com if you actually want to use this so that
we can discuss.

If you want to proceed anyway then here is what you need:

1. A host computer running Docker. I use the [[https://www.digitalocean.com/features/one-click-apps/docker/][Docker image from Digital Ocean]]

** Instructions
1. Clone this repository onto your local machine
2. On the server create a file in ~/secrets.sh. This file contains passwords
   and other other secret information the will be needed when the application runs. 
   See secrets-example.sh for details.
3. Run deploy-all.sh which ships stuff to the host and starts some bits up
4. You need to set a cronjob to run daily-cron.sh daily. This updates the database with new data each day.
    My cronjob looks like this: 
    
    0 4 * * * ~/daily-cron.sh | sed -e "s/^/$(date +'\%F \%T') /" >> /var/log/update.log 2>&1

** Still to do
The essence of any AdWords system is in three parts:

1. Something that can get the data out of AdWords and store it in a way that is easily queryable
2. Some kind of business specific magic that figures out what changes to make
3. Something that makes it easy to push changes back to AdWords.

A generalised way of doing part 2 is *way* out of scope here.

Cirrus is currently only a solution for part 1. An idea for part 3 is in the works right now.

