# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

webdatabase:
  user:     "_env:WEBUSER:web"
  password: "_env:WEBPASS:web"
  host:     "_env:POSTGRES_PORT_5432_TCP_ADDR:localhost"
  port:     "_env:POSTGRES_PORT_5432_TCP_PORT:5432"
  database: "_env:WEBDATABASE:web"
  poolsize: "_env:WEBPOOLSIZE:10"

adwordsdatabase:
  user:     "_env:ADWUSER:adwords"
  password: "_env:ADWPASS:adwords"
  host:     "_env:POSTGRES_PORT_5432_TCP_ADDR:localhost"
  port:     "_env:POSTGRES_PORT_5432_TCP_PORT:5432"
  database: "_env:ADWDATABASE:web"
  poolsize: "_env:ADWPOOLSIZE:10"
  
copyright: Insert copyright statement here
#analytics: UA-YOURCODE
